"use client";

import { useEffect, useRef } from "react";
import TypingEffect from "../ui/TypingEffect";
import Terminal from "../ui/Terminal";

type Props = {
  output: string;
  goal: string;
};

export default function OutputPanel({ output, goal }: Props) {
  const bottomRef = useRef<HTMLDivElement | null>(null);

  // 🔽 Auto-scroll when output updates
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [output]);

  // 📋 Copy output
  const handleCopy = () => {
    if (!output) return;
    navigator.clipboard.writeText(output);
  };

  // ⬇ Download output
  const handleDownload = () => {
    if (!output) return;

    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = "vera_output.txt";
    a.click();

    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-slate-800/60 border border-slate-700 rounded-xl p-4 h-[500px] flex flex-col glow-card">

      {/* HEADER */}
      <div className="flex justify-between items-center mb-2">
        <h2 className="text-purple-400 text-sm font-semibold tracking-wide">
          OUTPUT
        </h2>

        <div className="flex gap-2">
          <button
            onClick={handleCopy}
            className="text-xs px-2 py-1 bg-slate-700 hover:bg-slate-600 rounded"
          >
            Copy
          </button>

          <button
            onClick={handleDownload}
            className="text-xs px-2 py-1 bg-slate-700 hover:bg-slate-600 rounded"
          >
            Download
          </button>
        </div>
      </div>

      {/* CONTENT */}
      <div className="flex-1 overflow-y-auto text-sm space-y-3 pr-1">

        {!output && (
          <p className="text-gray-500">No output yet...</p>
        )}

        {/* 🎯 GOAL */}
        {goal && (
          <div>
            <h3 className="text-blue-400 font-semibold mb-1">
              🎯 Objective
            </h3>
            <p className="text-gray-300 whitespace-pre-wrap">
              {goal}
            </p>
          </div>
        )}

        {/* 🧠 SYSTEM NOTE */}
        {output && (
          <div className="text-xs text-gray-500">
            🧠 Generated by V.E.R.A Cognitive Engine
          </div>
        )}

        {/* ✅ RESULT (Terminal Styled) */}
        {output && (
          <Terminal title="RESULT" height="h-[220px]">
            <TypingEffect text={output} />
          </Terminal>
        )}

        <div ref={bottomRef} />
      </div>
    </div>
  );
}
